---
kind: pipeline
name: default

steps:
  - name: Version
    image: debian
    commands:
      - echo 1.5.3-openware > .tags
    when:
      branch:
        - master

  - name: "Build & Push to Openware Registry"
    image: plugins/docker
    settings:
      debug: true
      compress: true
      username:
        from_secret: ow_registry_username
      password:
        from_secret: ow_registry_password
      repo: reg.openware.work/openware/vault
      registry: reg.openware.work
      dockerfile: ./Dockerfile
    when:
      branch:
        - master

  - name: Build container
    image: plugins/docker
    settings:
      debug: true
      compress: true
      username:
        from_secret: quay_username
      password:
        from_secret: quay_password
      repo: quay.io/openware/vault
      registry: quay.io
      dockerfile: ./Dockerfile
    when:
      branch:
        - master

trigger:
  event:
    - push
